- name: Check for asdf
  stat: "path=~/.asdf"
  register: asdf_check

- name: Install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    version: "v0.9.0"
    dest: "~/.asdf"
  when: not asdf_check.stat.exists
