- name: Add vfox repo
  ansible.builtin.shell: |
    set -o pipefail
    if ! test -f /etc/apt/sources.list.d/versionfox.list; then
      echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | sudo tee /etc/apt/sources.list.d/versionfox.list
    fi
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Install dnf Packages
  ansible.builtin.package:
    name: "{{ dnf_pkgs }}"
  when: ansible_facts['os_family'] == "RedHat"
  become: true

- name: Install apt Packages
  ansible.builtin.package:
    name: "{{ apt_pkgs }}"
  when: ansible_facts['os_family'] == "Debian"
  become: true

- name: Symlink to user
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  when: ansible_facts['os_family'] == "Debian"
  loop:
    - { src: /usr/bin/batcat, dest: ~/.local/bin/bat }
    - { src: /usr/bin/fdfind, dest: ~/.local/bin/fd }
