- name: Make .config directory
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: "0755"

- name: Symlink config
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/fish/files"
    path: ~/.config/fish
    state: link
