- name: Dot files config
  hosts: local
  roles:
    - role: zsh
      tags: 
        - part1
        - zsh
      vars:
        zdotdir: ~/.config/zsh
    - role: omz
      tags: omz
      vars:
        oh_my_zsh_path: ~/.config/zsh/oh-my-zsh
        omz_plugins:
          - repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
            path: plugins/zsh-syntax-highlighting
          - repo: https://github.com/zsh-users/zsh-autosuggestions
            path: plugins/zsh-autosuggestions
          - repo: https://github.com/romkatv/powerlevel10k.git
            path: themes/powerlevel10k
    - role: tmux
      tags: tmux
    - role: devtools
      tags: devtools
      vars:
        homebrew_pkgs:
          - asdf
          - bat
          - docker
          - docker-compose
          - fd
          - fzf
          - git-delta
          - helm
          - jq
          - kubectx
          - luajit
          - ripgrep
          - stylua
          - vale
        # homebrew_casks:
        #   - alacritty
        dnf_pkgs:
          # - alacritty
          - bat
          - fd-find
          - fzf
          - git-delta
          - jq
          - luajit
          - podman
          - podman-compose
          - ripgrep
          - g++
          - wget
          - zip
          # - kubectx
          # - vale
          # - stylua
          # - helm
    - role: git
      tags: git
      vars:
        - git_email: 22567131+ec965@users.noreply.github.com
        - git_user: ec965
    - role: asdf
      tags: asdf
      vars:
        - programs:
            - name: nodejs
              repo: "https://github.com/asdf-vm/asdf-nodejs.git"
              version: "16.14.0"
            - name: golang
              repo: https://github.com/kennyp/asdf-golang.git
              version: latest
            - name: terraform
              repo: https://github.com/asdf-community/asdf-hashicorp.git
              version: latest
            - name: kubectl
              repo: https://github.com/asdf-community/asdf-kubectl.git
              version: latest
            - name: zig
              repo: https://github.com/asdf-community/asdf-zig.git
              version: latest
    - role: nodejs
      tags: nodejs
      vars:
        - npm_global_packages:
            - eslint
            - prettier
            - typescript
            - yarn
            - "@fsouza/prettierd"
    - role: nvim
      tags: nvim
    - role: link
      tags: link
      vars:
        - darwin_link_dirs:
            - file: "hammerspoon"
              target: "~/.hammerspoon"
    - role: vscode
      tags: vscode
    - role: fonts
      tags: fonts
    - role: alacritty
      tags: alacritty
      vars:
        - font_size: 12
        - font: JetBrainsMono Nerd Font Mono
