- name: Dot files config
  hosts: local
  pre_tasks:
    - name: Update Cache
      ansible.builtin.dnf:
        update_cache: true
        state: present
      when: ansible_facts['os_family'] == "RedHat"
  roles:
    - role: git
      tags: git
      vars:
        git_email: enoch965@gmail.com
        git_user: ec965
    - role: zsh
      tags: zsh
      vars:
        zdotdir: ~/.config/zsh
    - role: tmux
      tags: tmux
    - role: devtools
      tags: devtools
      vars:
        homebrew_pkgs:
          - ansible
          - ansible-lint
          - asdf
          - bat
          - fd
          - fnlfmt
          - fzf
          - git-delta
          - helm
          - jq
          - kubectx
          - luajit
          - luarocks
          - python
          - ripgrep
          - shellcheck
          - stylua
          - vale
        homebrew_casks:
          - alacritty
          - wezterm
          - linearmouse
          - rectangle
          - spaceid
        dnf_pkgs:
          - ShellCheck
          - bat
          - fd-find
          - fzf
          - g++
          - git-delta
          - jq
          - luajit
          - luarocks
          - podman
          - podman-compose
          - python
          - ripgrep
          - wget
          - zoxide
          - zip
        apt_pkgs:
          - bat
          - fd-find
          - fzf
          - jq
          - luajit
          - luarocks
          - ripgrep
          - shellcheck
          - zoxide
          - wget
          - zip
    - role: asdf
      tags: asdf
      vars:
        programs:
          - name: nodejs
            repo: "https://github.com/asdf-vm/asdf-nodejs.git"
            version: "16.15.1"
          - name: golang
            repo: https://github.com/kennyp/asdf-golang.git
            version: "1.18"
          - name: terraform
            repo: https://github.com/asdf-community/asdf-hashicorp.git
            version: 1.1.7
          - name: kubectl
            repo: https://github.com/asdf-community/asdf-kubectl.git
            version: 1.23.5
          - name: zig
            repo: https://github.com/asdf-community/asdf-zig.git
            version: 0.9.1
    - role: nodejs
      tags: nodejs
      vars:
        npm_global_packages:
          - eslint
          - prettier
          - typescript
          - yarn
          - "@fsouza/prettierd"
    - role: nvim
      tags: nvim
    - role: vscode
      tags: vscode
    - role: fonts
      tags: fonts
    - role: alacritty
      tags: alacritty
      vars:
        font_size: 14
        font: FantasqueSansM Nerd Font
        opacity: 0.85
    - role: wezterm
      tags: wezterm
      vars:
        font_size: 14
        font: FantasqueSansM Nerd Font
        opacity: 0.9
    - role: hammerspoon
      tags: hammerspoon
      when: ansible_facts['os_family'] == "Darwin"
    - role: skhd
      tags: skhd
      when: ansible_facts['os_family'] == "Darwin"
    - role: yabai
      tags: yabai
      when: ansible_facts['os_family'] == "Darwin"
