add_newline = false
format="""
$username\
$hostname\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$deno\
$golang\
$helm\
$lua\
$nodejs\
$python\
$rust\
$terraform\
$memory_usage\
$aws\
$env_var\
$custom\
$jobs\
$battery\
$status\
$shell\
$character"""

right_format = """$cmd_duration$time"""

[line_break]
disabled = true

# Right Side
[cmd_duration]
min_time = 500
format = "[$duration]($style)"

[time]
disabled = false
format = " [$time]($style)"

# Left Side
[username]
show_always = false
format = "[$user]($style)"

[git_branch]
format = "[$symbol$branch]($style) "

[hostname]
format = "@[$hostname]($style)"

[docker_context]
format = "[$symbol$context]($style) "

[deno]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"

[helm]
format = "[$symbol($version )]($style)"

[lua]
format = "[$symbol($version )]($style)"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[rust]
format = "[$symbol($version )]($style)"

[terraform]
format = "[$symbol$workspace]($style) "

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\])]($style)'

[gcloud]
format = 	'[$symbol$account(@$domain)(\($region\))]($style) '

[git_status]
format = '([$all_status$ahead_behind]($style) )'

[directory]
style = 'blue'

[character]
success_symbol = '[\$](bold green)'
error_symbol = '[\$](bold red)'

[nodejs]
format = '[$symbol($version )]($style)'
