- name: Create directory
  ansible.builtin.file:
    path: ~/.config/yabai
    state: directory
    mode: "0755"
    recurse: true

- name: Link Yabairc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/yabai/files/yabairc"
    path: ~/.config/yabai/yabairc
    state: link
