- name: Create directory
  ansible.builtin.file:
    path: ~/Library/Application Support/Code/User
    state: directory
    recurse: true
    mode: "0755"
  when: ansible_facts['os_family'] == "Darwin"

- name: Link VSCode settings
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/vscode/files/{{ item }}"
    path: "~/Library/Application Support/Code/User/{{ item }}"
    state: link
  when: ansible_facts['os_family'] == "Darwin"
  loop:
    - settings.json
    - keybindings.json
