- name: Create directory
  ansible.builtin.file:
    path: ~/.config/Code/User
    state: directory
    recurse: true
    mode: "0755"

- name: Link VSCode settings
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/vscode/files/{{ item }}"
    path: ~/.config/Code/User/{{ item }}
    state: link
  loop: 
    - settings.json
    - keybindings.json
