- name: Install nodejs asdf plugin
  shell: "if ! asdf plugin list | grep -q 'nodejs'; then asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git ; fi"
- name: Install nodejs 16
  shell: "if ! asdf list nodejs | grep -q '{{ node_version }}'; then asdf install nodejs {{ node_version }}; fi"
- name: Set global node version
  shell: "asdf global nodejs {{ node_version }}"
- name: Install npm global packages
  npm:
    name: "{{ item }}"
    global: yes
  loop: "{{ npm_global_packages }}"
