- name: Create directories for files
  file:
    path: "{{ item.target | dirname }}"
    state: directory
    mode: '0755'
    recurse: true
  loop: "{{ link_files }}"

- name: Link files
  file:
    src: "{{ ansible_env.PWD }}/roles/link/files/{{ item.file }}"
    path: "{{ item.target }}"
    state: link
  loop: "{{ link_files }}"

- name: Darwin Link directories
  file:
    src: "{{ ansible_env.PWD }}/roles/link/files/{{ item.file }}"
    path: "{{ item.target }}"
    state: link
  loop: "{{ darwin_link_dirs }}"
  when: ansible_facts['os_family'] == "Darwin"
