- name: Install zsh
  apt: 
    name: zsh
    state: present
  become: 'yes'
  # zsh is preinstalled on MacOS
  when: ansible_facts['os_family'] == "Debian"

- name: Make ZDOTDIR
  file: 
    path: "{{ zdotdir }}"
    state: directory
    mode: '0755'

- name: Link home zshenv
  file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/home.zshenv"
    path: ~/.zshenv
    state: link

- name: Link zdotdir zshenv
  file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/dot.zshenv"
    path: "{{ zdotdir }}/.zshenv"
    state: link

- name: Link zshrc
  file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/dot.zshrc"
    path: "{{ zdotdir }}/.zshrc"
    state: link

- name: Check for Oh my Zsh
  stat: "path={{ oh_my_zsh_path }}"
  register: oh_my_zsh

- name: Install Oh my Zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ oh_my_zsh_path }}"
    depth: 1
  when: not oh_my_zsh.stat.exists

- name: Install omz plugins
  include_tasks: omzplugin.yml
  loop: "{{ omz_plugins }}"
