- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true
  # zsh is preinstalled on MacOS
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"

- name: Make ZDOTDIR
  ansible.builtin.file:
    path: "{{ zdotdir }}"
    state: directory
    mode: '0755'

- name: Link home zshenv
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/home.zshenv"
    path: ~/.zshenv
    state: link

- name: Link zdotdir zshenv
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/dot.zshenv"
    path: "{{ zdotdir }}/.zshenv"
    state: link

- name: Link zshrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/dot.zshrc"
    path: "{{ zdotdir }}/.zshrc"
    state: link

- name: change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
