- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
  become: true
  # zsh is preinstalled on MacOS
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"

- name: Make ZDOTDIR
  ansible.builtin.file:
    path: "{{ zdotdir }}"
    state: directory
    mode: "0755"

- name: Link home zshenv
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/home.zshenv"
    path: ~/.zshenv
    state: link

- name: Link zdotdir zshenv
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/dot.zshenv"
    path: "{{ zdotdir }}/.zshenv"
    state: link

- name: Link zshrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/dot.zshrc"
    path: "{{ zdotdir }}/.zshrc"
    state: link

- name: Install Antidote
  ansible.builtin.git:
    repo: https://github.com/mattmc3/antidote.git
    dest: "{{ zdotdir }}/antidote"
    depth: 1
    version: HEAD
    update: true

- name: Link zsh-plugins.txt
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/dot.zsh_plugins.txt"
    path: "{{ zdotdir }}/.zsh_plugins.txt"
    state: link

- name: Change user shell to zsh
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh

- name: Link MacMachine.zshrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/macmachine.zsh"
    path: "{{ zdotdir }}/machine.zsh"
    state: link
  when: ansible_facts['os_family'] == "Darwin"

- name: Link Linux.zshrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/zsh/files/linuxmachine.zsh"
    path: "{{ zdotdir }}/machine.zsh"
    state: link
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"
