- name: Check if gitconfig exists
  stat: path="~/.gitconfig"
  register: gitconfig_stat

- name: Back up gitconfig
  command: mv ~/.gitconfig ~/.gitconfig.bak
  args:
    creates: "~/.gitconfig.bak"
  when: gitconfig_stat.stat.exists

- name: Update gitconfig
  template:
    src: "gitconfig.j2"
    dest: ~/.gitconfig
