- name: Check if gitconfig exists
  ansible.builtin.stat: path="~/.gitconfig"
  register: gitconfig_stat

- name: Back up gitconfig
  ansible.builtin.command: mv ~/.gitconfig ~/.gitconfig.bak
  args:
    creates: "~/.gitconfig.bak"
  when: gitconfig_stat.stat.exists

- name: Update gitconfig
  ansible.builtin.template:
    src: "gitconfig.j2"
    dest: ~/.gitconfig
    mode: 0664
