- name: Create directory
  ansible.builtin.file:
    path: ~/.config/wezterm
    state: directory
    mode: "0755"
    recurse: true

- name: Check if wezterm lua config exists
  ansible.builtin.stat: path="~/.config/wezterm/wezterm.lua"
  register: wezterm_stat

- name: Back up config
  ansible.builtin.command: mv ~/.config/wezterm/wezterm.lua ~/.config/wezterm/wezterm.lua.bak
  args:
    creates: "~/.config/wezterm/wezterm.lua.bak"
  when: wezterm_stat.stat.exists

- name: Update wezterm config
  ansible.builtin.template:
    src: "wezterm.j2"
    dest: ~/.config/wezterm/wezterm.lua
    mode: 0664
