- import_tasks: install_darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
- import_tasks: install_linux.yml
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"

- name: Make .config directory
  ansible.builtin.file:
    path: ~/.config/tmux
    state: directory
    mode: "0755"
    recurse: "yes"

- name: Symlink config
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/tmux/files/tmux.conf"
    path: ~/.config/tmux/tmux.conf
    state: link
