- import_tasks: install_darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
- import_tasks: install_linux.yml
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"

- name: Download Vim Plug
  ansible.builtin.command: >
    sh -c 'curl -fLo $HOME/.local/share/nvim/site/autoload/plug.vim --create-dirs
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  args:
    creates: ~/.local/share/nvim/site/autoload/plug.vim

- name: Make plugin directory
  ansible.builtin.file:
    path: ~/.config/plugged
    state: directory
    mode: '0755'

- name: Make .config directory
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: '0755'

- name: Symlink vimrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/nvim/files"
    path: ~/.config/nvim
    state: link

- name: Install plugins
  ansible.builtin.command: nvim --headless +'PlugInstall --sync' +qall
  args:
    creates: ~/.config/plugged/*
