- import_tasks: install_darwin.yml
  when: ansible_facts['os_family'] == "Darwin"
- import_tasks: install_linux.yml
  when: ansible_facts['os_family'] == "Debian" or ansible_facts['os_family'] == "RedHat"

- name: Download Vim Plug
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    depth: 1
    version: master

- name: Make .config directory
  ansible.builtin.file:
    path: ~/.config
    state: directory
    mode: "0755"

- name: Symlink vimrc
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/nvim/files"
    path: ~/.config/nvim
    state: link
