- name: Link fonts Linux
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/fonts/files"
    path: "~/.fonts"
    state: link
  when:
    ansible_facts['os_family'] == "RedHat" or ansible_facts['os_family'] ==
    "Debian"

- name: Link fonts Darwin
  ansible.builtin.file:
    src: "{{ ansible_env.PWD }}/roles/fonts/files"
    path: "~/Library/Fonts"
    state: hard # macos isn't detecting fonts that are symlinked
  when: ansible_facts['os_family'] == "Darwin"
